server:
  port: 8080
  servlet:
    context-path: ""

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs

spring:
  data:
    mongodb:
      password: crs
      username: crs
      database: citizen
#      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG